apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-plugin-risk-scorecard-backend
  namespace: default
data:
  GITHUB_APP_ID: "827078"
  GITHUB_INSTALLATION_ID: "48036152"
  GITHUB_PRIVATE_KEY_BASE64_ENCODED: "projects/457384642040/secrets/GITHUB_APP_PRIVATE_KEY_DEV/versions/1"
  RISC_FOLDER_PATH: ".security/risc"
  JSON_SCHEMA_BASE_URL: "https://kartverket.github.io/backstage-plugin-risk-scorecard-backend"
  ENTRA_ID_TENANT_ID: "c6ea0b0b-e867-46d4-a70b-4c05887e7f6f"
  SOPS_AGE_KEY: "secret key"
  FILENAME_PREFIX: "risc"
  FILENAME_POSTFIX: "risc"